apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: us-east-1

managedNodeGroups:
- name: epense
  instanceTypes: [m5.large]
  desiredCapacity: 3
  spot: true


